version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - ${DB_PORT}:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-ppassword']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    cap_add:
      - SYS_NICE

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${PORT}']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
