version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-ppassword']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    cap_add:
      - SYS_NICE

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - mysql
    build:
      context: .
      target: dependencies
    ports:
      - 3333:3333
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch
